import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Banner from '../components/Banner'
import hero_image from '../public/assets/hero-image.png'
import Card from '../components/card/Card'

import coffeeStores from '../data/coffee-stores.json'

export default function Home({ data }) {
    const handleOnClickButton = () => {
        console.log('view coffee location')
    }
    return (
        <div className={styles.container}>
            <Head>
                <title>Coffee Connoisseur</title>
                <meta
                    name="description"
                    content="Generated by Coffee Connoisseur"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Banner
                    buttonText={'View stores nearby'}
                    handleOnClickButton={handleOnClickButton}
                />
                <div className={styles.heroImage}>
                    <Image
                        src={hero_image}
                        alt="hero"
                        width={700}
                        height={400}
                    />
                </div>
                {coffeeStores.length > 0 && (
                    <>
                        <h2 className={styles.heading2}>Lagos Coffee</h2>
                        <div className={styles.cardLayout}>
                            {data.map((coffeeStore) => (
                                <Card
                                    name={coffeeStore.name}
                                    imgUrl={coffeeStore.imgUrl}
                                    href={`/coffee-store/${coffeeStore.id}`}
                                    className={styles.card}
                                    key={coffeeStore.id}
                                />
                            ))}
                        </div>
                    </>
                )}
            </main>
        </div>
    )
}

export async function getStaticProps(context) {
    return {
        props: { data: coffeeStores }, // will be passed to the page component as props
    }
}
