import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from '../components/Banner'
import { fetchData } from '../lib/coffee-store'
import useTrackLocation from '../hooks/use-track-location'
import { useContext, useEffect, useState } from 'react'
import { ACTION_TYPES } from '../context/type'
import { StoreContext } from '../context/store'
import CoffeeStoresItem from '../components/coffeeStores/CoffeeStoresItem'

export default function Home({ coffeeStores }) {
    const { handleTrackLocation, locationErrorMsg, isFindingLocation } =
        useTrackLocation()

    const [coffeeStoreError, setCoffeeStoreError] = useState(null)
    const { dispatch, state } = useContext(StoreContext)

    useEffect(() => {
        const setCoffeeStoresByLocation = async () => {
            if (state.latLong) {
                try {
                    const fetchedCoffeeStores = await fetchData(
                        state.latLong,
                        30
                    )
                    dispatch({
                        type: ACTION_TYPES.SET_COFFEE_STORES,
                        payload: { coffeeStores: fetchedCoffeeStores },
                    })
                } catch (error) {
                    console.log(error)
                    setCoffeeStoreError(error.message)
                }
            }
        }

        setCoffeeStoresByLocation()
    }, [state.latLong, dispatch])

    const handleOnClickButton = () => {
        handleTrackLocation()
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Coffee Connoisseur</title>
                <meta
                    name="description"
                    content="Generated by Coffee Connoisseur"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Banner
                    buttonText={
                        isFindingLocation ? 'Locating...' : 'View stores nearby'
                    }
                    handleOnClickButton={handleOnClickButton}
                />
                {locationErrorMsg && (
                    <h6>Something went wrong: {locationErrorMsg}</h6>
                )}
                {coffeeStoreError && (
                    <h6>Something went wrong: {coffeeStoreError}</h6>
                )}
                <CoffeeStoresItem
                    coffeeStores={state.coffeeStores}
                    heading="Coffee Store near me"
                />
                <CoffeeStoresItem
                    coffeeStores={coffeeStores}
                    heading="Lagos Coffee Store"
                />
            </main>
        </div>
    )
}

export async function getStaticProps(context) {
    const coffeeStores = await fetchData()
    return {
        props: { coffeeStores }, // will be passed to the page component as props
    }
}
